services:
  db:
    image: mongo:8
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://localhost:27017/test
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  back:
    build: ./back
    image: mljdigitiaacr.azurecr.io/back:latest
    container_name: back
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DJANGO_SECRET_KEY: "my_secret_key"
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DATABASE_NAME: "digit_recognizer"
      DATABASE_HOST: "db"
      DATABASE_PORT: "27017"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "gunicorn --workers=4 --timeout 300 --bind 0.0.0.0:8000 back.wsgi:application"

  celery:
    build: ./back
    image: mljdigitiaacr.azurecr.io/celery:latest
    container_name: celery
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./back:/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DATABASE_NAME: "digit_recognizer"
      DATABASE_HOST: "db"
      DATABASE_PORT: "27017"
    entrypoint: /app/entrypoint.sh

  front:
    build: ./front
    image: mljdigitiaacr.azurecr.io/front:latest
    container_name: front
    depends_on:
      - back
    ports:
      - "3000:80"

volumes:
  mongo_data:
